[package]
name = "web-app-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-http-server = { tag = "0.9.0", git = "https://github.com/MyJetTools/my-http-server.git" }
is-alive-middleware = { tag = "0.9.0", git = "https://github.com/MyJetTools/is-alive-middleware.git" }
my-logger = { tag = "1.3.0", git = "https://github.com/MyJetTools/my-logger.git" }
rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git" }
rust-common = { tag = "0.1.1", git = "https://github.com/MyJetTools/rust-common.git", default-features = false, features = [
    "user_agent",
] }
async-trait = "*"
lazy_static = "*"

# static files serving - our own implementation, since the root folder of the content
# is chosen per request (desktop/mobile), and we fully control the caching headers
base64 = "*"
sha2 = "*"
flate2 = "*"
zstd = "*"

tokio = { version = "*", features = ["full"] }
